[package]
name = "jlox"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
ascii = "1.1.0"
clap = { version = "4.5.4", features = ["derive"] }
derive_more = { version = "1.0.0-beta.6", features = ["debug"]}
phf = { version = "0.11.2", features = ["macros"] }
thiserror = "1.0.61"
